#!/bin/bash
echo "Setting up Apache..."
apt install apache2

echo "Enabling Apache SSL, Headers & Rewrite modules..."
a2enmod ssl
a2enmod headers
a2enmod rewrite

echo "Restarting Apache..."
service apache2 restart
