#!/bin/bash
echo "Setting up Apache..."
apt install apache2

echo "Enabling Apache SSL, Headers & Rewrite modules..."
a2enmod ssl
a2enmod headers
a2enmod rewrite

echo "Restarting Apache..."
service apache2 restart

echo "Only retain logs for 7 days. Original logrotate config: /etc/logrotate.d/apache2.bak"
sudo sed -i.bak 's/\brotate\ .*\b/rotate\ 7/g' /etc/logrotate.d/apache2
