#!/bin/bash
#
echo "Setting up Apache..."
apt-get install apache2

# This is duplication:
# echo "Installing Apache modules..."
# apt-get install php libapache2-mod-php php-mcrypt php-mysql

echo "Enabling Apache SSL, Headers & Rewrite modules..."
a2enmod ssl
a2enmod headers
a2enmod rewrite

echo "Restarting Apache..."
service apache2 restart
