#!/bin/bash
#
# Install MariaDB
# ------------------------------------------------------------------------------
# Import key and add repository
echo "Importing Key and repository for MariaDB..."
apt-get install software-properties-common
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://lon1.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu xenial main'

# Install
echo "Installing MariaDB..."
apt update
apt install mariadb-server

# Make secure
echo "Make MariaDB secure..."
mysql_secure_installation

# Pin
echo "Pinnng the MariaDB repo - see `/etc/apt/preferences.d/mariadb.pref`."
touch /etc/apt/preferences.d/mariadb.pref
cat > /etc/apt/preferences.d/mariadb.pref <<EOF
Package: *
Pin: origin lon1.mirrors.digitalocean.com
Pin-Priority: 1000
EOF
